### PR TITLE
using toolset instead of target-os to select openssl libraries when using openssl >= 1.1

### PR DESCRIPTION
**Pull request by aldenml**
Hi @cas-- , do you mind looking at this? Thanks

### CODE REVIEW

**Comment by arvidn** [comment]
the mingw build seems to have a problem with this.

**Comment by arvidn** [comment]
I wonder if this is not a function of the toolset but rather whether you're linking against an msvc-build of openssl or a msys-build of openssl.

**Comment by arvidn** [comment]
I believe I made this change in RC_1_1 too, but I can back-port it later

**Comment by cas--** [comment]
I don't think it should be replacing target for toolset for pre-1.1. 

This needs appveyor to test with OpenSSL 1.1, especially since that is now the recommended release.

**Comment by arvidn** [comment]
> I don't think it should be replacing target for toolset for pre-1.1.

I think it depends on whether one links against an "msvc-build" or an msys-build. I would expect the msys builds to always have been named "libcrypto" and "libssl", even before 1.1.

**Comment by cas--** [comment]
I mentioned it because the pre-1.1 with target was working fine before the libcrypto name changes.

The change for 1.1 from target to toolset is supported by the change here: https://github.com/radiator-software/p5-net-ssleay/pull/29/files

**Comment by aldenml** [comment]
I also don't think it's wise to mix a `libtorrent` msys build with an `openssl` msvc build, I will take a look at this later

**Comment by aldenml** [comment]
@arvidn I know this fix is the absolute minimum to get it work for me, but making appveyor to work with openssl-1.1+ is a big time consuming task.

@cas-- do you see any problem with this minimal change for now?

**Comment by aldenml** [comment]
any idea of what happened here? https://ci.appveyor.com/project/arvidn/libtorrent/builds/20690878/job/4y2n46fl23ctpexa

**Comment by aldenml** [comment]
it looks like `bjam` find that both conditions apply and can't select one...interesting...

**Comment by cas--** [comment]
lgtm :+1:

**Comment by aldenml** [comment]
sure, done
