### ISSUE TITLE
1.1.10 fails to build in the presence of the 1.1.9 version

### ISSUE THREAD

**Issue by yurivict** [arvidn/libtorrent#3324]
Errors:
```
udp_tracker.cpp:(.text._ZN11udp_tracker14on_udp_receiveERKN5boost6system10error_codeEmPNS0_4asio2ip14basic_endpointINS6_3udpEEEPci[_ZN11udp_tracker14on_udp_receiveERKN5boost6system10error_codeEmPNS0_4asio2ip14basic_endpointINS6_3udpEEEPci]+0x435): undefined reference to `libtorrent::print_endpoint(boost::asio::ip::basic_endpoint<boost::asio::ip::udp> const&)'
./.libs/libtest.a(peer_server.o): In function `peer_server::thread_fun()':
peer_server.cpp:(.text._ZN11peer_server10thread_funEv[_ZN11peer_server10thread_funEv]+0x44): undefined reference to `libtorrent::condition_variable::~condition_variable()'
peer_server.cpp:(.text._ZN11peer_server10thread_funEv[_ZN11peer_server10thread_funEv]+0xe0): undefined reference to `libtorrent::condition_variable::condition_variable()'
peer_server.cpp:(.text._ZN11peer_server10thread_funEv[_ZN11peer_server10thread_funEv]+0x25e): undefined reference to `libtorrent::condition_variable::~condition_variable()'
peer_server.cpp:(.text._ZN11peer_server10thread_funEv[_ZN11peer_server10thread_funEv]+0x303): undefined reference to `libtorrent::condition_variable::~condition_variable()'
c++: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1
```

OS: FreeBSD 11.2

If I would update the port, I would get many complaints from people who build from source on machines with 1.1.9 installed. This happened before with other ports.

Besides, this problem makes it error-prone when this dependency on old headers doesn't cause an obvious failure, but silently leads to wrong compilation.

**Comment by yurivict** [comment]
This problem only exists in gmake-based build, but not in cmake-based build.

**Comment by arvidn** [comment]
do you have a suggestion of how to solve it?
In the long run I'm hoping to remove use of autoconf

**Comment by yurivict** [comment]
Just remove autoconf/gnu tools. cmake works fine.

**Comment by arvidn** [comment]
My impression is that the cmake files still can't package a source tarball, but perhaps I'm wrong about that

**Comment by arvidn** [comment]
I've started the effort to remove autotools https://github.com/arvidn/libtorrent/pull/3351
I'm not sure it will make it into 1.2.0 though, as it's also a kind of big change, it may have to wait until the next major release
