### ISSUE TITLE
Randomly failing boost dependency

### ISSUE THREAD

**Issue by lyssdod** [arvidn/libtorrent#1121]
Hi again,

I'm using 1.0.9 release and randomly hitting the issue of missing `boost/intrusive_ptr.hpp` header when compiling on OSX. The libtorrent library itself compiles fine, the issue begins when I'm including `libtorrent/add_torrent_params.hpp` which specifies `boost/intrusive_ptr.hpp` as dependency. 

Systems always hitting this: OSX 10.10, 10.11, boost installed from homebrew (1.61):
```
[ 85%] Building CXX object CMakeFiles/node-libtorrent-ng.dir/src/add_torrent_params.cpp.o
In file included from /tmp/node-libtorrent/src/add_torrent_params.cpp:5:
/tmp/node-libtorrent/deps/libtorrent/include/libtorrent/add_torrent_params.hpp:38:10: fatal error: 
      'boost/intrusive_ptr.hpp' file not found
#include <boost/intrusive_ptr.hpp>
         ^
1 error generated.
```
It seems to build with boost 1.55:
https://travis-ci.org/lyssdod/node-libtorrent/jobs/161145741#L891

As I see from boost website, the file is still in place:
http://www.boost.org/doc/libs/1_61_0/boost/intrusive_ptr.hpp

What can cause this?

**Comment by arvidn** [comment]
the translation unit you build, that includes the libtorrent header, probably doesn't have the appropriate include path specified to find boost headers. For instance, you may want to install boost vis homebrew or macports, OR you can just download and unzip it somewhere and make sure to add that include path.

**Comment by lyssdod** [comment]
I've figured out that it was using system headers mixed with the headers I provided. Once I make a forced include of my headers (boost 1.61), the problem perished. Thanks!
