### ISSUE TITLE
Fails to build with Boost 1.70.0

### ISSUE THREAD

**Issue by jbeich** [arvidn/libtorrent#3683]
Environment:
```
FreeBSD clang version 8.0.0 (branches/release_80 354130) (based on LLVM 8.0.0)
Target: x86_64-unknown-freebsd13.0
Thread model: posix
InstalledDir: /usr/bin
```

RC_1_2 (f5cf102e3) regressed after boostorg/asio@a72fbb0b867f:
```c++
In file included from src/i2p_stream.cpp:37:
In file included from include/libtorrent/i2p_stream.hpp:45:
include/libtorrent/proxy_base.hpp:249:17: error: no member named 'get_io_service' in 'boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>'
                return m_sock.get_io_service();
                       ~~~~~~ ^
In file included from src/http_stream.cpp:33:
In file included from include/libtorrent/http_stream.hpp:38:
include/libtorrent/proxy_base.hpp:249:17: error: no member named 'get_io_service' in 'boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>'
                return m_sock.get_io_service();
                       ~~~~~~ ^
In file included from src/alert.cpp:42:
In file included from include/libtorrent/torrent.hpp:51:
In file included from include/libtorrent/peer_list.hpp:47:
In file included from include/libtorrent/ip_voter.hpp:40:
In file included from include/libtorrent/aux_/session_interface.hpp:46:
In file included from include/libtorrent/aux_/session_udp_sockets.hpp:36:
In file included from include/libtorrent/utp_socket_manager.hpp:39:
In file included from include/libtorrent/aux_/socket_type.hpp:42:
In file included from include/libtorrent/utp_stream.hpp:37:
include/libtorrent/udp_socket.hpp:64:50: error: no member named 'get_io_service' in 'boost::asio::basic_datagram_socket<boost::asio::ip::udp, boost::asio::executor>'
                io_service& get_io_service() { return m_socket.get_io_service(); }
                                                      ~~~~~~~~ ^
In file included from src/alert.cpp:42:
In file included from include/libtorrent/torrent.hpp:52:
include/libtorrent/tracker_manager.hpp:262:51: error: no member named 'get_io_service' in 'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>'
                io_service& get_io_service() { return m_timeout.get_io_service(); }
                                                      ~~~~~~~~~ ^
src/http_connection.cpp:151:11: error: no member named 'get_io_service' in 'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>'
                m_timer.get_io_service().post(std::bind(&http_connection::callback
                ~~~~~~~ ^
src/http_connection.cpp:163:11: error: no member named 'get_io_service' in 'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>'
                m_timer.get_io_service().post(std::bind(&http_connection::callback
                ~~~~~~~ ^
src/http_connection.cpp:261:11: error: no member named 'get_io_service' in 'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>'
                m_timer.get_io_service().post(std::bind(&http_connection::callback
                ~~~~~~~ ^
src/http_connection.cpp:300:13: error: no member named 'get_io_service' in 'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>'
                                m_timer.get_io_service().post(std::bind(&http_connection::callback
                                ~~~~~~~ ^
src/http_connection.cpp:335:15: error: no member named 'get_io_service' in 'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>'
                                                m_timer.get_io_service().post(std::bind(&http_connection::callback
                                                ~~~~~~~ ^
src/http_connection.cpp:347:34: error: no member named 'get_io_service' in 'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>'
                instantiate_connection(m_timer.get_io_service()
                                       ~~~~~~~ ^
src/http_connection.cpp:356:13: error: no member named 'get_io_service' in 'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>'
                                m_timer.get_io_service().post(std::bind(&http_connection::callback
                                ~~~~~~~ ^
src/http_connection.cpp:365:12: error: no member named 'get_io_service' in 'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>'
                        m_timer.get_io_service().post(std::bind(&http_connection::callback
                        ~~~~~~~ ^
```

master (735424f15) regressed after boostorg/asio@59066d80b26e:
```c++
In file included from src/choker.cpp:37:
In file included from include/libtorrent/torrent.hpp:52:
include/libtorrent/tracker_manager.hpp:265:53: error: no viable conversion from returned value of type 'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>::executor_type' (aka 'boost::asio::executor') to function return type 'io_context::executor_type'
                io_context::executor_type get_executor() { return m_timeout.get_executor(); }
                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/io_context.hpp:623:19: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>::executor_type' (aka 'boost::asio::executor') to 'const boost::asio::io_context::executor_type &' for 1st argument
class io_context::executor_type
                  ^
/usr/local/include/boost/asio/io_context.hpp:623:19: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>::executor_type' (aka 'boost::asio::executor') to 'boost::asio::io_context::executor_type &&' for 1st argument
/usr/local/include/boost/asio/executor.hpp:199:3: note: candidate function
  operator unspecified_bool_type() const BOOST_ASIO_NOEXCEPT
  ^
src/http_connection.cpp:340:3: error: no matching function for call to 'instantiate_connection'
                instantiate_connection(m_timer.get_executor().context()
                ^~~~~~~~~~~~~~~~~~~~~~
include/libtorrent/aux_/instantiate_connection.hpp:45:28: note: candidate function not viable: cannot bind base class object of type 'boost::asio::execution_context' to derived class reference 'boost::asio::io_context &' for 1st argument
        TORRENT_EXTRA_EXPORT bool instantiate_connection(io_context& exec
                                  ^
```

**Comment by fxcoudert** [comment]
We (Homebrew) are seeing this issue on macOS as well: https://github.com/Homebrew/homebrew-core/pull/38890

**Comment by jbeich** [comment]
`master` branch is still broken.

**Comment by arvidn** [comment]
addressing master here: https://github.com/arvidn/libtorrent/pull/3794
