### ISSUE TITLE
[Python binding] session_stats_metrics() doesn't work in ver 1.1.1.0

### ISSUE THREAD

**Issue by MaChengxin** [arvidn/libtorrent#1946]
_libtorrent version (or branch):_
1.1.1.0 from NixOS packages (attribute name: libtorrentRasterbar)

_platform/architecture:_
Ubuntu 16.04, x64

_compiler and compiler version:_
gcc (GCC) 5.4.0

_Python version:_
Python 2.7.13 (in Nix)

_please describe what symptom you see, what you would expect to see instead and
how to reproduce it._
I am trying to interpret the array returned by `session.post_session_stats()` in the alerts. As the documentation suggests I need to "always query the metrics first" by calling `session_stats_metrics()`.
I was expecting some output that makes sense. However I got the following error:
```
Traceback (most recent call last):
  File "simple_client.py", line 20, in <module>
    lt.session_stats_metrics()
AttributeError: 'module' object has no attribute 'session_stats_metrics'
```
How to reproduce: just import `libtorrent` as `lt` and call `lt.session_stats_metrics()` in Python's interactive mode.

**Comment by arvidn** [comment]
this has already been fixed in the 1.1.x branch. https://github.com/arvidn/libtorrent/blob/RC_1_1/bindings/python/src/session.cpp#L998

**Comment by MaChengxin** [comment]
FYI: after building `libtorrent` on my machine instead of using the Nix one, my problem is solved.
