### PR TITLE
enable SO_REUSEADDR on windows

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by sledgehammer999** [comment]
Latest RC_1_0 builds fine with msvc2015 + boost 1.60. But this fails with:

```
BOOST_ROOT = G:\QBITTORRENT\boost_1_60_0
CXXFLAGS =
LDFLAGS =
OS = NT
Performing configuration checks

    - 32-bit                   : yes (cached)
    - arm                      : no  (cached)
    - mips1                    : no  (cached)
    - power                    : no  (cached)
    - sparc                    : no  (cached)
    - x86                      : yes (cached)
    - symlinks supported       : no  (cached)
    - junctions supported      : yes (cached)
    - hardlinks supported      : yes (cached)
...patience...
...patience...
...found 2271 targets...
...updating 84 targets...
compile-c-c++ bin\fbb6849860e05552e890f21a8f6c4413\src\alert.obj
alert.cpp
G:\QBITTORRENT\libtorrent\include\libtorrent/socket.hpp(139): error C2062: type 'int' unexpected
G:\QBITTORRENT\libtorrent\include\libtorrent/socket.hpp(139): error C2334: unexpected token(s) preceding ':'; skipping apparent function body
G:\QBITTORRENT\libtorrent\include\libtorrent/peer.hpp(40): error C2143: syntax error: missing ';' before 'namespace'
G:\QBITTORRENT\boost_1_60_0\boost/integer_fwd.hpp(29): error C2039: 'uintmax_t': is not a member of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer_fwd.hpp(20): note: see declaration of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer_fwd.hpp(30): error C2039: 'intmax_t': is not a member of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer_fwd.hpp(20): note: see declaration of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer_fwd.hpp(31): error C2039: 'uintmax_t': is not a member of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer_fwd.hpp(20): note: see declaration of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer_fwd.hpp(107): error C2039: 'long_long_type': is not a member of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer_fwd.hpp(20): note: see declaration of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer_fwd.hpp(107): error C2061: syntax error: identifier 'long_long_type'
G:\QBITTORRENT\boost_1_60_0\boost/integer_fwd.hpp(111): error C2913: explicit specialization; 'libtorrent::boost::int_max_value_t' is not a specialization of a class template
G:\QBITTORRENT\boost_1_60_0\boost/integer_fwd.hpp(114): error C2039: 'long_long_type': is not a member of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer_fwd.hpp(20): note: see declaration of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer_fwd.hpp(114): error C2061: syntax error: identifier 'long_long_type'
G:\QBITTORRENT\boost_1_60_0\boost/integer_fwd.hpp(118): error C2913: explicit specialization; 'libtorrent::boost::int_min_value_t' is not a specialization of a class template
G:\QBITTORRENT\boost_1_60_0\boost/integer_fwd.hpp(121): error C2039: 'ulong_long_type': is not a member of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer_fwd.hpp(20): note: see declaration of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer_fwd.hpp(121): error C2061: syntax error: identifier 'ulong_long_type'
G:\QBITTORRENT\boost_1_60_0\boost/integer_fwd.hpp(125): error C2913: explicit specialization; 'libtorrent::boost::uint_value_t' is not a specialization of a class template
G:\QBITTORRENT\boost_1_60_0\boost/integer_fwd.hpp(167): error C2039: 'uintmax_t': is not a member of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer_fwd.hpp(20): note: see declaration of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(61): error C2039: 'long_long_type': is not a member of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(37): note: see declaration of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(61): error C3646: 'least': unknown override specifier
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(61): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(70): error C2039: 'ulong_long_type': is not a member of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(37): note: see declaration of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(70): error C3646: 'least': unknown override specifier
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(70): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(104): error C2039: 'long_long_type': is not a member of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(37): note: see declaration of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(104): error C2065: 'long_long_type': undeclared identifier
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(104): error C2766: explicit specialization; 'libtorrent::boost::detail::exact_signed_base_helper<8>' has already been defined
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(84): note: see previous definition of 'exact_signed_base_helper<8>'
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(105): error C2039: 'ulong_long_type': is not a member of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(37): note: see declaration of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(105): error C2065: 'ulong_long_type': undeclared identifier
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(105): error C2766: explicit specialization; 'libtorrent::boost::detail::exact_unsigned_base_helper<8>' has already been defined
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(85): note: see previous definition of 'exact_unsigned_base_helper<8>'
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(122): error C2065: 'long_long_type': undeclared identifier
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(132): note: see reference to class template instantiation 'libtorrent::boost::int_t<Bits>' being compiled
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(153): error C2065: 'long_long_type': undeclared identifier
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(165): note: see reference to class template instantiation 'libtorrent::boost::uint_t<Bits>' being compiled
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(171): error C2039: 'long_long_type': is not a member of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(37): note: see declaration of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(171): error C2061: syntax error: identifier 'long_long_type'
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(190): error C2913: explicit specialization; 'libtorrent::boost::int_max_value_t' is not a specialization of a class template
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(193): error C2039: 'long_long_type': is not a member of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(37): note: see declaration of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(193): error C2061: syntax error: identifier 'long_long_type'
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(212): error C2913: explicit specialization; 'libtorrent::boost::int_min_value_t' is not a specialization of a class template
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(216): error C2039: 'ulong_long_type': is not a member of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(37): note: see declaration of 'libtorrent::boost'
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(216): error C2061: syntax error: identifier 'ulong_long_type'
G:\QBITTORRENT\boost_1_60_0\boost/integer.hpp(257): error C2913: explicit specialization; 'libtorrent::boost::uint_value_t' is not a specialization of a class template
G:\QBITTORRENT\boost_1_60_0\boost/type_traits/has_trivial_destructor.hpp(30): error C2143: syntax error: missing ',' before '<'
G:\QBITTORRENT\boost_1_60_0\boost/type_traits/has_trivial_destructor.hpp(30): note: see reference to class template instantiation 'libtorrent::boost::has_trivial_destructor<T>' being compiled
G:\QBITTORRENT\boost_1_60_0\boost/type_traits/has_trivial_destructor.hpp(39): error C2504: 'false_type': base class undefined
G:\QBITTORRENT\boost_1_60_0\boost/type_traits/has_trivial_destructor.hpp(41): error C2504: 'false_type': base class undefined
G:\QBITTORRENT\boost_1_60_0\boost/type_traits/has_trivial_destructor.hpp(42): error C2504: 'false_type': base class undefined
G:\QBITTORRENT\boost_1_60_0\boost/type_traits/has_trivial_destructor.hpp(43): error C2504: 'false_type': base class undefined
G:\QBITTORRENT\boost_1_60_0\boost/type_traits/is_union.hpp(20): error C2143: syntax error: missing ',' before '<'
G:\QBITTORRENT\boost_1_60_0\boost/type_traits/is_union.hpp(20): note: see reference to class template instantiation 'libtorrent::boost::is_union<T>' being compiled
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(98): error C2039: 'sp_typeinfo': is not a member of 'libtorrent::boost::detail'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(80): note: see declaration of 'libtorrent::boost::detail'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(98): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(98): error C2143: syntax error: missing ';' before '*'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(98): error C2238: unexpected token(s) preceding ';'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(169): error C2653: 'mpl': is not a class or namespace name
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(183): note: see reference to class template instantiation 'libtorrent::boost::detail::function::get_function_tag<F>' being compiled
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(169): error C2143: syntax error: missing ';' before '<'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(169): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(171): error C2238: unexpected token(s) preceding ';'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(173): error C2653: 'mpl': is not a class or namespace name
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(173): error C2059: syntax error: '<'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(175): error C2238: unexpected token(s) preceding ';'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(177): error C2653: 'mpl': is not a class or namespace name
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(177): error C2059: syntax error: '<'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(179): error C2238: unexpected token(s) preceding ';'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(182): error C3646: 'type': unknown override specifier
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(182): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(352): error C2653: 'mpl': is not a class or namespace name
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(434): note: see reference to class template instantiation 'libtorrent::boost::detail::function::functor_manager<Functor>' being compiled
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(352): error C2061: syntax error: identifier 'true_'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(360): error C2653: 'mpl': is not a class or namespace name
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(360): error C2061: syntax error: identifier 'false_'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(361): error C2535: 'void libtorrent::boost::detail::function::functor_manager<Functor>::manager(const libtorrent::boost::detail::function::function_buffer &,libtorrent::boost::detail::function::function_buffer &,libtorrent::boost::detail::function::functor_manager_operation_type)': member function already defined or declared
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(351): note: see declaration of 'libtorrent::boost::detail::function::functor_manager<Functor>::manager'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(453): error C2653: 'mpl': is not a class or namespace name
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(537): note: see reference to class template instantiation 'libtorrent::boost::detail::function::functor_manager_a<Functor,Allocator>' being compiled
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(453): error C2061: syntax error: identifier 'true_'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(461): error C2653: 'mpl': is not a class or namespace name
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(461): error C2061: syntax error: identifier 'false_'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(462): error C2535: 'void libtorrent::boost::detail::function::functor_manager_a<Functor,Allocator>::manager(const libtorrent::boost::detail::function::function_buffer &,libtorrent::boost::detail::function::function_buffer &,libtorrent::boost::detail::function::functor_manager_operation_type)': member function already defined or declared
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(452): note: see declaration of 'libtorrent::boost::detail::function::functor_manager_a<Functor,Allocator>::manager'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(630): error C2039: 'sp_typeinfo': is not a member of 'libtorrent::boost::detail'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(80): note: see declaration of 'libtorrent::boost::detail'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(630): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(630): error C2143: syntax error: missing ';' before '&'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(631): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(623): error C2789: 'libtorrent::boost::function_base::sp_typeinfo': an object of const-qualified type must be initialized
G:\QBITTORRENT\boost_1_60_0\boost/function/function_base.hpp(630): note: see declaration of 'libtorrent::boost::function_base::sp_typeinfo'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(243): error C2653: 'mpl': is not a class or namespace name
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(255): note: see reference to class template instantiation 'libtorrent::boost::detail::function::get_function_invoker2<FunctionPtr,R,T0,T1>' being compiled
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(243): error C2143: syntax error: missing ';' before '<'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(243): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(254): error C2238: unexpected token(s) preceding ';'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(264): error C2653: 'mpl': is not a class or namespace name
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(276): note: see reference to class template instantiation 'libtorrent::boost::detail::function::get_function_obj_invoker2<FunctionObj,R,T0,T1>' being compiled
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(264): error C2143: syntax error: missing ';' before '<'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(264): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(275): error C2238: unexpected token(s) preceding ';'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(285): error C2653: 'mpl': is not a class or namespace name
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(297): note: see reference to class template instantiation 'libtorrent::boost::detail::function::get_function_ref_invoker2<FunctionObj,R,T0,T1>' being compiled
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(285): error C2143: syntax error: missing ';' before '<'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(285): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(296): error C2238: unexpected token(s) preceding ';'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(308): error C2653: 'mpl': is not a class or namespace name
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(320): note: see reference to class template instantiation 'libtorrent::boost::detail::function::get_member_invoker2<MemberPtr,R,T0,T1>' being compiled
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(308): error C2143: syntax error: missing ';' before '<'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(308): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(319): error C2238: unexpected token(s) preceding ';'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(570): error C2653: 'mpl': is not a class or namespace name
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(650): note: see reference to class template instantiation 'libtorrent::boost::detail::function::basic_vtable2<R,T0,T1>' being compiled
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(570): error C2061: syntax error: identifier 'true_'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(576): error C2653: 'mpl': is not a class or namespace name
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(576): error C2061: syntax error: identifier 'true_'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(584): error C2653: 'mpl': is not a class or namespace name
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(584): error C2061: syntax error: identifier 'false_'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(587): error C2535: 'void libtorrent::boost::detail::function::basic_vtable2<R,T0,T1>::assign_functor(FunctionObj,libtorrent::boost::detail::function::function_buffer &) const': member function already defined or declared
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(570): note: see declaration of 'libtorrent::boost::detail::function::basic_vtable2<R,T0,T1>::assign_functor'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(590): error C2653: 'mpl': is not a class or namespace name
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(590): error C2061: syntax error: identifier 'false_'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(601): error C2535: 'void libtorrent::boost::detail::function::basic_vtable2<R,T0,T1>::assign_functor_a(FunctionObj,libtorrent::boost::detail::function::function_buffer &,Allocator) const': member function already defined or declared
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(576): note: see declaration of 'libtorrent::boost::detail::function::basic_vtable2<R,T0,T1>::assign_functor_a'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(718): error C2988: unrecognizable template declaration/definition
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(1012): note: see reference to class template instantiation 'libtorrent::boost::function2<R,T0,T1>' being compiled
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(720): error C2143: syntax error: missing ',' before '<'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(718): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(730): error C2988: unrecognizable template declaration/definition
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(732): error C2143: syntax error: missing ',' before '<'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(730): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(781): error C2988: unrecognizable template declaration/definition
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(781): error C2143: syntax error: missing ';' before '<'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(781): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(781): error C2238: unexpected token(s) preceding ';'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(781): error C2059: syntax error: '<'
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(801): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
G:\QBITTORRENT\boost_1_60_0\boost/function/function_template.hpp(801): fatal error C1003: error count exceeds 100; stopping compilation

    call "C:\Users\SLEDGE~1\AppData\Local\Temp\b2_msvc_14.0_vcvarsall_x86.cmd" >nul
cl /Zm800 -nologo @"bin\fbb6849860e05552e890f21a8f6c4413\src\alert.obj.rsp" 

...failed compile-c-c++ bin\fbb6849860e05552e890f21a8f6c4413\src\alert.obj...
...failed updating 1 target...

```

**Comment by sledgehammer999** [comment]
Testing again now.

**Comment by sledgehammer999** [comment]
It finished building. I am building qbt now.
PS: Don't forget to squash your commits into one (`git rebase -i <hash>` is your friend)

**Comment by arvidn** [comment]
I always do :)
