### PR TITLE
fix build with boost 1.70.0

### LINKED ISSUE #3683: Fails to build with Boost 1.70.0
Environment:
```
FreeBSD clang version 8.0.0 (branches/release_80 354130) (based on LLVM 8.0.0)
Target: x86_64-unknown-freebsd13.0
Thread model: posix
InstalledDir: /usr/bin
```

RC_1_2 (f5cf102e3) regressed after boostorg/asio@a72fbb0b867f:
```c++
In file included from src/i2p_stream.cpp:37:
In file included from include/libtorrent/i2p_stream.hpp:45:
include/libtorrent/proxy_base.hpp:249:17: error: no member named 'get_io_service' in 'boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>'
                return m_sock.get_io_service();
                       ~~~~~~ ^
In file included from src/http_stream.cpp:33:
In file included from include/libtorrent/http_stream.hpp:38:
include/libtorrent/proxy_base.hpp:249:17: error: no member named 'get_io_service' in 'boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>'
                return m_sock.get_io_service();
                       ~~~~~~ ^
In file included from src/alert.cpp:42:
In file included from include/libtorrent/torrent.hpp:51:
In file included from include/libtorrent/peer_list.hpp:47:
In file included from include/libtorrent/ip_voter.hpp:40:
In file included from include/libtorrent/aux_/session_interface.hpp:46:
In file included from include/libtorrent/aux_/session_udp_sockets.hpp:36:
In file included from include/libtorrent/utp_socket_manager.hpp:39:
In file included from include/libtorrent/aux_/socket_type.hpp:42:
In file included from include/libtorrent/utp_stream.hpp:37:
include/libtorrent/udp_socket.hpp:64:50: error: no member named 'get_io_service' in 'boost::asio::basic_datagram_socket<boost::asio::ip::udp, boost::asio::executor>'
                io_service& get_io_service() { return m_socket.get_io_service(); }
                                                      ~~~~~~~~ ^
In file included from src/alert.cpp:42:
In file included from include/libtorrent/torrent.hpp:52:
include/libtorrent/tracker_manager.hpp:262:51: error: no member named 'get_io_service' in 'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>'
                io_service& get_io_service() { return m_timeout.get_io_service(); }
                                                      ~~~~~~~~~ ^
src/http_connection.cpp:151:11: error: no member named 'get_io_service' in 'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>'
                m_timer.get_io_service().post(std::bind(&http_connection::callback
                ~~~~~~~ ^
src/http_connection.cpp:163:11: error: no member named 'get_io_service' in 'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>'
                m_timer.get_io_service().post(std::bind(&http_connection::callback
                ~~~~~~~ ^
src/http_connection.cpp:261:11: error: no member named 'get_io_service' in 'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>'
                m_timer.get_io_service().post(std::bind(&http_connection::callback
                ~~~~~~~ ^
src/http_connection.cpp:300:13: error: no member named 'get_io_service' in 'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>'
                                m_timer.get_io_service().post(std::bind(&http_connection::callback
                                ~~~~~~~ ^
src/http_connection.cpp:335:15: error: no member named 'get_io_service' in 'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>'
                                                m_timer.get_io_service().post(std::bind(&http_connection::callback
                                                ~~~~~~~ ^
src/http_connection.cpp:347:34: error: no member named 'get_io_service' in 'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>'
                instantiate_connection(m_timer.get_io_service()
                                       ~~~~~~~ ^
src/http_connection.cpp:356:13: error: no member named 'get_io_service' in 'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>'
                                m_timer.get_io_service().post(std::bind(&http_connection::callback
                                ~~~~~~~ ^
src/http_connection.cpp:365:12: error: no member named 'get_io_service' in 'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>'
                        m_timer.get_io_service().post(std::bind(&http_connection::callback
                        ~~~~~~~ ^
```

master (735424f15) regressed after boostorg/asio@59066d80b26e:
```c++
In file included from src/choker.cpp:37:
In file included from include/libtorrent/torrent.hpp:52:
include/libtorrent/tracker_manager.hpp:265:53: error: no viable conversion from returned value of type 'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>::executor_type' (aka 'boost::asio::executor') to function return type 'io_context::executor_type'
                io_context::executor_type get_executor() { return m_timeout.get_executor(); }
                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/io_context.hpp:623:19: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>::executor_type' (aka 'boost::asio::executor') to 'const boost::asio::io_context::executor_type &' for 1st argument
class io_context::executor_type
                  ^
/usr/local/include/boost/asio/io_context.hpp:623:19: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>::executor_type' (aka 'boost::asio::executor') to 'boost::asio::io_context::executor_type &&' for 1st argument
/usr/local/include/boost/asio/executor.hpp:199:3: note: candidate function
  operator unspecified_bool_type() const BOOST_ASIO_NOEXCEPT
  ^
src/http_connection.cpp:340:3: error: no matching function for call to 'instantiate_connection'
                instantiate_connection(m_timer.get_executor().context()
                ^~~~~~~~~~~~~~~~~~~~~~
include/libtorrent/aux_/instantiate_connection.hpp:45:28: note: candidate function not viable: cannot bind base class object of type 'boost::asio::execution_context' to derived class reference 'boost::asio::io_context &' for 1st argument
        TORRENT_EXTRA_EXPORT bool instantiate_connection(io_context& exec
                                  ^
```

### PR DESCRIPTION
**Pull request by ffontaine**
Fix #3683

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

File: include/libtorrent/config.hpp [hunk 1]
```diff
@@ -56,6 +57,14 @@ POSSIBILITY OF SUCH DAMAGE.
 #pragma GCC diagnostic ignored "-Wformat-extra-args"
 #endif
 
+// ====== BOOST ========
+
+#if BOOST_VERSION >= 107000
+#define GET_IO_SERVICE(s) ((boost::asio::io_context&)(s).get_executor().context())
```
Comment (arvidn) [inline include/libtorrent/config.hpp]: I would rather not use a macro for this. Also, I'm not a fan of the reinterpret cast. Is there a reason calling `get_executor()` doesn't work without the cast?
Also, I think the `get_executor()` call dates back quite far, to boost-1.66 or so. So I *think* it would be reasonable to just require a new version of boost and replace all calls to `get_io_service()` with `get_executor().context()` instead.

I made this change in `master`, and I think it should be done in the same way in `RC_1_2`, to make the merge simpler. (i.e. merge of `RC_1_2` into `master`)

File: src/http_connection.cpp [hunk 2]
```diff
@@ -148,7 +148,7 @@ void http_connection::get(std::string const& url, time_duration timeout, int pri
 
 	if (ec)
 	{
-		m_timer.get_io_service().post(std::bind(&http_connection::callback
```
Comment (arvidn) [inline src/http_connection.cpp]: iirc, all calls to `post()` like this could be changed to use the free function version of `post()`. like this: `post(m_timer, std::bind(...))`

File: include/libtorrent/config.hpp (hunk 1 above)
Comment (arvidn) [reply include/libtorrent/config.hpp]: If you think it's better to have an abstraction like this, to support older versions of boost, please make it an inline function instead

Comment (ffontaine) [reply include/libtorrent/config.hpp]: OK, I can remove the fallback and bump boost requirement from 1.54 to 1.66.
Concerning the reinterpret_cast, without it, build fails on: 
```
../include/libtorrent/proxy_base.hpp: In member function ‘libtorrent::io_service& libtorrent::proxy_base::get_io_service()’:
../include/libtorrent/proxy_base.hpp:249:39: error: invalid initialization of reference of type ‘libtorrent::io_service& {aka boost::asio::io_context&}’ from expression of type ‘boost::asio::execution_context’
   return m_sock.get_executor().context();
```

File: src/http_connection.cpp (hunk 2 above)
Comment (ffontaine) [reply src/http_connection.cpp]: I'll need your help on this one. From my understanding, you want to call:
```
template <typename ExecutionContext, typename CompletionToken>
inline BOOST_ASIO_INITFN_RESULT_TYPE(CompletionToken, void()) post(
    ExecutionContext& ctx, BOOST_ASIO_MOVE_ARG(CompletionToken) token,
    typename enable_if<is_convertible<
      ExecutionContext&, execution_context&>::value>::type*)
```
However, this fails (probably because of the enable_if argument) on:
```

http_connection.cpp: In member function ‘void libtorrent::http_connection::get(const string&, libtorrent::time_duration, int, const libtorrent::aux::proxy_settings*, int, const string&, const boost::optional<boost::asio::ip::address>&, libtorrent::resolver_flags, const string&, libtorrent::i2p_connection*)’:
http_connection.cpp:152:27: error: no matching function for call to ‘post(libtorrent::deadline_timer&, std::_Bind_helper<false, void (libtorrent::http_connection::*)(boost::system::error_code, libtorrent::span<char>), std::shared_ptr<libtorrent::http_connection>&, boost::system::error_code&, libtorrent::span<char> >::type)’
    , me, ec, span<char>{}));
                           ^
In file included from /home/fabrice/buildroot-test/buildroot/output/host/sh4-buildroot-linux-uclibc/sysroot/usr/include/boost/asio/post.hpp:113:0,
                 from /home/fabrice/buildroot-test/buildroot/output/host/sh4-buildroot-linux-uclibc/sysroot/usr/include/boost/asio/basic_socket.hpp:28,
                 from /home/fabrice/buildroot-test/buildroot/output/host/sh4-buildroot-linux-uclibc/sysroot/usr/include/boost/asio/basic_socket_acceptor.hpp:19,
                 from /home/fabrice/buildroot-test/buildroot/output/host/sh4-buildroot-linux-uclibc/sysroot/usr/include/boost/asio/ip/tcp.hpp:19,
                 from ../include/libtorrent/socket.hpp:53,
                 from ../include/libtorrent/http_connection.hpp:51,
                 from http_connection.cpp:33:
/home/fabrice/buildroot-test/buildroot/output/host/sh4-buildroot-linux-uclibc/sysroot/usr/include/boost/asio/impl/post.hpp:79:63: note: candidate: template<class ExecutionContext, class CompletionToken> typename boost::asio::async_result<typename std::decay<_Arg>::type, void()>::return_type boost::asio::post(ExecutionContext&, CompletionToken&&, typename std::enable_if<std::is_convertible<ExecutionContext&, boost::asio::execution_context&>::value>::type*)
 inline BOOST_ASIO_INITFN_RESULT_TYPE(CompletionToken, void()) post(
                                                               ^~~~
/home/fabrice/buildroot-test/buildroot/output/host/sh4-buildroot-linux-uclibc/sysroot/usr/include/boost/asio/impl/post.hpp:79:63: note:   template argument deduction/substitution failed:
/home/fabrice/buildroot-test/buildroot/output/host/sh4-buildroot-linux-uclibc/sysroot/usr/include/boost/asio/impl/post.hpp: In substitution of ‘template<class ExecutionContext, class CompletionToken> typename boost::asio::async_result<typename std::decay<_Arg>::type, void()>::return_type boost::asio::post(ExecutionContext&, CompletionToken&&, typename std::enable_if<std::is_convertible<ExecutionContext&, boost::asio::execution_context&>::value>::type*) [with ExecutionContext = boost::asio::basic_waitable_timer<std::chrono::_V2::system_clock>; CompletionToken = std::_Bind<void (libtorrent::http_connection::*(std::shared_ptr<libtorrent::http_connection>, boost::system::error_code, libtorrent::span<char>))(boost::system::error_code, libtorrent::span<char>)>]’:
http_connection.cpp:152:27:   required from here
/home/fabrice/buildroot-test/buildroot/output/host/sh4-buildroot-linux-uclibc/sysroot/usr/include/boost/asio/impl/post.hpp:79:63: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
/home/fabrice/buildroot-test/buildroot/output/host/sh4-buildroot-linux-uclibc/sysroot/usr/include/boost/asio/impl/post.hpp:70:56: note: candidate: template<class Executor, class CompletionToken> typename boost::asio::async_result<typename std::decay<_Arg>::type, void()>::return_type boost::asio::post(const Executor&, CompletionToken&&, typename std::enable_if<boost::asio::is_executor<Executor>::value>::type*)
 BOOST_ASIO_INITFN_RESULT_TYPE(CompletionToken, void()) post(
                                                        ^~~~
/home/fabrice/buildroot-test/buildroot/output/host/sh4-buildroot-linux-uclibc/sysroot/usr/include/boost/asio/impl/post.hpp:70:56: note:   template argument deduction/substitution failed:
/home/fabrice/buildroot-test/buildroot/output/host/sh4-buildroot-linux-uclibc/sysroot/usr/include/boost/asio/impl/post.hpp: In substitution of ‘template<class Executor, class CompletionToken> typename boost::asio::async_result<typename std::decay<_Arg>::type, void()>::return_type boost::asio::post(const Executor&, CompletionToken&&, typename std::enable_if<boost::asio::is_executor<Executor>::value>::type*) [with Executor = boost::asio::basic_waitable_timer<std::chrono::_V2::system_clock>; CompletionToken = std::_Bind<void (libtorrent::http_connection::*(std::shared_ptr<libtorrent::http_connection>, boost::system::error_code, libtorrent::span<char>))(boost::system::error_code, libtorrent::span<char>)>]’:
http_connection.cpp:152:27:   required from here
/home/fabrice/buildroot-test/buildroot/output/host/sh4-buildroot-linux-uclibc/sysroot/usr/include/boost/asio/impl/post.hpp:70:56: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
/home/fabrice/buildroot-test/buildroot/output/host/sh4-buildroot-linux-uclibc/sysroot/usr/include/boost/asio/impl/post.hpp:62:56: note: candidate: template<class CompletionToken> typename boost::asio::async_result<typename std::decay<_Tp>::type, void()>::return_type boost::asio::post(CompletionToken&&)
 BOOST_ASIO_INITFN_RESULT_TYPE(CompletionToken, void()) post(
                                                        ^~~~
/home/fabrice/buildroot-test/buildroot/output/host/sh4-buildroot-linux-uclibc/sysroot/usr/include/boost/asio/impl/post.hpp:62:56: note:   template argument deduction/substitution failed:
http_connection.cpp:152:27: note:   candidate expects 1 argument, 2 provided
    , me, ec, span<char>{}));
   
```

**Comment by arvidn** [comment]
at a second thought, I think it makes more sense to stay as backwards compatible as possible with older boost versions in `RC_1_2`. It is the stable branch, so changes should be conservative I think.

I can propose some changes to this patch.
