### ISSUE TITLE
Fails to build with Boost 1.69 (develop snapshot)

### ISSUE THREAD

**Issue by jbeich** [arvidn/libtorrent#3378]
libtorrent version (or branch): `RC_1_1` (12c52e875113)
platform/architecture: FreeBSD 11.2 amd64
compiler and compiler version: Clang/libc++ 6.0

After boostorg/system@2fa0a00583a3a7 build fails. See [error log](https://ptpb.pw/VNhq).

```c++
In file included from src/choker.cpp:34:
In file included from include/libtorrent/peer_connection.hpp:46:
In file included from include/libtorrent/chained_buffer.hpp:37:
include/libtorrent/disk_io_job.hpp:78:12: error: expected class name
                , boost::noncopyable
                         ^
```

**Comment by arvidn** [comment]
does this fix it? https://github.com/arvidn/libtorrent/pull/3383

**Comment by jbeich** [comment]
#3383 builds fine now with boost 1.69 now.

**Comment by jbeich** [comment]
Another bustage due to boostorg/system@2fa0a00583a3a7 probably caused by `using` statements, see [error log](https://ptpb.pw/oLxi).
https://github.com/arvidn/libtorrent/blob/a5da48edd4be7f858d56724e4a82902e10b91ec6/bindings/python/src/error_code.cpp#L46-L48
```
bindings/python/src/error_code.cpp:119:10: error:
      no matching member function for call to 'def'
        .def("message", &error_category::message)
        ~^~~
/usr/local/include/boost/python/class.hpp:229:11: note: candidate template ignored: couldn't infer template
      argument 'F'
    self& def(char const* name, F f)
          ^
/usr/local/include/boost/python/class.hpp:219:11: note: candidate function template not viable: requires single
      argument 'visitor', but 2 arguments were provided
    self& def(def_visitor<Derived> const& visitor)
          ^
/usr/local/include/boost/python/class.hpp:238:11: note: candidate function template not viable: requires 3
      arguments, but 2 were provided
    self& def(char const* name, A1 a1, A2 const& a2)
          ^
/usr/local/include/boost/python/class.hpp:245:11: note: candidate function template not viable: requires 4
      arguments, but 2 were provided
    self& def(char const* name, Fn fn, A1 const& a1, A2 const& a2)
          ^
/usr/local/include/boost/python/class.hpp:261:11: note: candidate function template not viable: requires 5
      arguments, but 2 were provided
    self& def(char const* name, Fn fn, A1 const& a1, A2 const& a2, A3 const& a3)
          ^
bindings/python/src/error_code.cpp:127:10: error:
      no matching member function for call to 'def'
        .def("message", &error_code::message)
        ~^~~
/usr/local/include/boost/python/class.hpp:229:11: note: candidate template ignored: couldn't infer template
      argument 'F'
    self& def(char const* name, F f)
          ^
/usr/local/include/boost/python/class.hpp:219:11: note: candidate function template not viable: requires single
      argument 'visitor', but 2 arguments were provided
    self& def(def_visitor<Derived> const& visitor)
          ^
/usr/local/include/boost/python/class.hpp:238:11: note: candidate function template not viable: requires 3
      arguments, but 2 were provided
    self& def(char const* name, A1 a1, A2 const& a2)
          ^
/usr/local/include/boost/python/class.hpp:245:11: note: candidate function template not viable: requires 4
      arguments, but 2 were provided
    self& def(char const* name, Fn fn, A1 const& a1, A2 const& a2)
          ^
/usr/local/include/boost/python/class.hpp:261:11: note: candidate function template not viable: requires 5
      arguments, but 2 were provided
    self& def(char const* name, Fn fn, A1 const& a1, A2 const& a2, A3 const& a3)
          ^
2 errors generated.
```

**Comment by jbeich** [comment]
Still fails, see [error log](https://ptpb.pw/gikh):
```c++
In file included from bindings/python/src/error_code.cpp:44:
In file included from bindings/python/src/boost_python.hpp:9:
In file included from /usr/local/include/boost/python.hpp:11:
In file included from /usr/local/include/boost/python/args.hpp:22:
In file included from /usr/local/include/boost/python/object_core.hpp:14:
In file included from /usr/local/include/boost/python/call.hpp:15:
In file included from /usr/local/include/boost/python/converter/arg_to_python.hpp:10:
In file included from /usr/local/include/boost/python/to_python_indirect.hpp:11:
In file included from /usr/local/include/boost/python/object/make_ptr_instance.hpp:8:
In file included from /usr/local/include/boost/python/object/make_instance.hpp:10:
In file included from /usr/local/include/boost/python/converter/registered.hpp:11:
In file included from /usr/local/include/boost/python/converter/registry.hpp:9:
In file included from /usr/local/include/boost/python/converter/rvalue_from_python_data.hpp:10:
/usr/local/include/boost/python/detail/destroy.hpp:20:13: error: '~error_category' is a protected member of 'boost::system::error_category'
        p->~T();
            ^
/usr/local/include/boost/python/detail/destroy.hpp:52:8: note: in instantiation of function template specialization 'boost::python::detail::value_destroyer<false>::execute<boost::system::error_category>' requested here
    >::execute((const volatile T*)p);
       ^
/usr/local/include/boost/python/detail/destroy.hpp:58:5: note: in instantiation of function template specialization 'boost::python::detail::destroy_referent_impl<const boost::system::error_category>' requested here
    destroy_referent_impl(p, (T(*)())0);
    ^
/usr/local/include/boost/python/converter/rvalue_from_python_data.hpp:135:25: note: in instantiation of function template specialization 'boost::python::detail::destroy_referent<const boost::system::error_category &>' requested here
        python::detail::destroy_referent<ref_type>(this->storage.bytes);
                        ^
/usr/local/include/boost/python/converter/arg_from_python.hpp:106:8: note: in instantiation of member function 'boost::python::converter::rvalue_from_python_data<const boost::system::error_category &>::~rvalue_from_python_data' requested here
struct arg_rvalue_from_python
       ^
/usr/local/include/boost/python/object/py_function.hpp:38:16: note: in instantiation of member function 'boost::python::detail::caller_arity<2>::impl<_object *(*)(boost::system::error_category &, const boost::system::error_category &), boost::python::default_call_policies, boost::mpl::vector3<_object *, boost::system::error_category &, const boost::system::error_category &> >::operator()' requested here
        return m_caller(args, kw);
               ^
/usr/local/include/boost/python/object/py_function.hpp:32:5: note: (skipping 6 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
    caller_py_function_impl(Caller const& caller)
    ^
/usr/local/include/boost/python/operators.hpp:152:14: note: in instantiation of function template specialization 'boost::python::class_<boost::system::error_category, boost::noncopyable_::noncopyable, boost::python::detail::not_specified, boost::python::detail::not_specified>::def<_object *(*)(boost::system::error_category &, const boost::system::error_category &)>' requested here
          cl.def(
             ^
/usr/local/include/boost/python/def_visitor.hpp:31:29: note: in instantiation of function template specialization 'boost::python::detail::operator_<boost::python::detail::op_eq, boost::python::self_ns::self_t, boost::python::self_ns::self_t>::visit<boost::python::class_<boost::system::error_category, boost::noncopyable_::noncopyable, boost::python::detail::not_specified, boost::python::detail::not_specified> >' requested here
        v.derived_visitor().visit(c);
                            ^
/usr/local/include/boost/python/def_visitor.hpp:67:29: note: in instantiation of function template specialization 'boost::python::def_visitor_access::visit<boost::python::def_visitor<boost::python::detail::operator_<boost::python::detail::op_eq, boost::python::self_ns::self_t, boost::python::self_ns::self_t> >, boost::python::class_<boost::system::error_category, boost::noncopyable_::noncopyable, boost::python::detail::not_specified, boost::python::detail::not_specified> >' requested here
        def_visitor_access::visit(*this, c);
                            ^
/usr/local/include/boost/python/class.hpp:221:17: note: in instantiation of function template specialization 'boost::python::def_visitor<boost::python::detail::operator_<boost::python::detail::op_eq, boost::python::self_ns::self_t, boost::python::self_ns::self_t> >::visit<boost::python::class_<boost::system::error_category, boost::noncopyable_::noncopyable, boost::python::detail::not_specified, boost::python::detail::not_specified> >' requested here
        visitor.visit(*this);
                ^
bindings/python/src/error_code.cpp:120:10: note: in instantiation of function template specialization 'boost::python::class_<boost::system::error_category, boost::noncopyable_::noncopyable, boost::python::detail::not_specified, boost::python::detail::not_specified>::def<boost::python::detail::operator_<boost::python::detail::op_eq, boost::python::self_ns::self_t, boost::python::self_ns::self_t> >' requested here
        .def(self == self)
         ^
/usr/local/include/boost/system/error_code.hpp:195:5: note: declared protected here
    ~error_category() = default;
    ^
1 error generated.
```

**Comment by arvidn** [comment]
there doesn't seem to be a way to bind a type that cannot be destructed with boost.python

**Comment by arvidn** [comment]
I haven't been able to get the `develop` branch of boost to work for me yet, so I can't test these fixes locally. I made another attempt to make boost.python not generate a destructor for the category type.
Next step will probably be to put more effort into building with the boost `develop` branch

**Comment by jbeich** [comment]
Still fails, similar to https://github.com/arvidn/libtorrent/issues/3378#issuecomment-433636410, see [error log](https://ptpb.pw/onhd). Anyway, to reproduce try:
1. Install Boost (preferably 1.68)
2. Clone [System repo](https://github.com/boostorg/system/)
3. Add `-I/path/to/system/include` to `CXXFLAGS`
4. Build

OR

3. Build against system Boost but save the build log
4. Copy the command line that builds `error_code.cpp` from the log
5. Prepend `-I/path/to/system/include` just after `CXX`
6. Build just the file

**Comment by arvidn** [comment]
ok, I finally had some time to look into this. I think https://github.com/arvidn/libtorrent/pull/3389 is good now. At least it builds against boost develop in the configurations I tested

**Comment by jbeich** [comment]
Thanks. Builds fine (tested: [python 2.7](https://ptpb.pw/2M91) and [python 3.6](https://ptpb.pw/ydWr)) for me as well.

**Comment by jbeich** [comment]
Also, linking against `-lboost_system` is not required since Boost 1.69. My `-Wl,-z,defs` build [succeeded](https://ptpb.pw/wZST) without the following line:
https://github.com/arvidn/libtorrent/blob/RC_1_1/CMakeLists.txt#L323
