### ISSUE TITLE
Please help with compiling in Visual Studio 2015/17

### ISSUE THREAD

**Issue by lunatichai** [arvidn/libtorrent#2897]
libtorrent version (or branch):  1.1.6
platform/architecture: windows 7 x64
compiler and compiler version: msvc14.0 and msvc 14.1

Can't compile simple projects with libtorrent, for example
```
int main(int argc, char* argv[])
{
    using namespace libtorrent;
    session s;
    return 0;
}
```
With msvc2017 x64 i've got errors:
- main.obj:-1: error: LNK2019: unresolved external symbol "void __cdecl libtorrent::ipv6_deprecated_(void)" (?ipv6_deprecated_@libtorrent@@YAXXZ)

- main.obj:-1: error: LNK2019: unresolved external symbo "public: __cdecl libtorrent::session::~session(void)" (??1session@libtorrent@@QEAA@XZ)

- main.obj:-1: error: LNK2019: unresolved external symbo "private: void __cdecl libtorrent::session::start(int,struct libtorrent::settings_pack const &,class boost::asio::io_context *)" (?start@session@libtorrent@@AEAAXHAEBUsettings_pack@2@PEAVio_context@asio@boost@@@Z)

With VS15:
- Error	LNK2001	unresolved external symbol "void __cdecl libtorrent::ipv6_deprecated_(void)" (?ipv6_deprecated_@libtorrent@@YAXXZ)

- Error	LNK2001	unresolved external symbol "private: void __thiscall libtorrent::session::start(int,struct libtorrent::settings_pack const &,class boost::asio::io_context *)" (?start@session@libtorrent@@AAEXHABUsettings_pack@2@PAVio_context@asio@boost@@@Z)	

- Error	LNK2001	unresolved external symbol "public: __thiscall libtorrent::session::~session(void)" (??1session@libtorrent@@QAE@XZ)

- Severity	Code	Description	Project	File	Line	Suppression State Error	LNK2001	unresolved external symbol _WinMain@16	

My steps: 
1 - download boost 1.66
2- create .bat (instruction from https://studiofreya.com/2017/04/23/building-boost-1-64-with-visual-studio-2017/) and build with set msvcver=msvc-14.0 and 14.1
3- copy b2 and bjam to libtorrent folder
4- build libtorrent with parameters:
    for msvc14.0 x86: b2 --toolset=msvc-14.0 variant=release link=static runtime-link=static dht=on -sBOOST_ROOT="c:\local\boost_1_66_0"
    for msvc14.1 x64: b2 --toolset=msvc-14.1 address-model=64  variant=release link=static runtime-link=static dht=on -sBOOST_ROOT="c:\local\boost_1_66_0"
5-create simple project. For first i cerated project in Qt Creator, choosed include/lib of boost and libtorrent with msvc2017 x64 and got same errors. Then i try with Visual Studio 15: add boost folder and libtorrent\include toC\C++->General->AdditionalIncludeDirectories, add boost\stage\win32\lib and .\libtorrent-master\..\threading-multi in Configur.Property->Linker->General->AdditionalLibraryDirectories

Please, help me with this problems. If possible give me detail manual

**Comment by LiMinggang** [comment]
Did you try to move the "using namespace" outside the main function?

**Comment by lunatichai** [comment]
Yes. I tried to build examples too

**Comment by LiMinggang** [comment]
I used/use VS 2015/VS 2017 and boost 1.66 to build libtorrent master with no problem for X64.

The only difference I can tell based on your description is that the boost build listed in your reference page using "runtime-link=shared"----I'm not sure you changed it to static or not.

**Comment by lunatichai** [comment]
I think i miss something importante. Can you write manual how you build? From boost to example project. Than you!

**Comment by LiMinggang** [comment]
Nothing special than yours except I don't use QT.
Boost:
.\bjam.exe define=_WIN32_WINNT=0x0601 --with-thread --with-system --with-filesystem
--with-regex --with-iostreams threading=multi variant=release link=static
address-model=64 runtime-link=static stage

You have to make sure using same /MT or /MD in different projects. 
If you want more details about the options I used to tune libtorrent, see #2512

**Comment by lunatichai** [comment]
Thank you for reply but i can't build project. I don't understand what's wrong. Can you tell me step by step or give me project

**Comment by arvidn** [comment]
@lunatichai from the error message, it looks like you're not linking against libtorrent. in your linker settings, make sure to include the actual libtorrent library that was produced by building it. I would expect it to be called ``libtorrent.lib``.
