### ISSUE TITLE
Fails to build against Boost 1.67

### ISSUE THREAD

**Issue by jbeich** [arvidn/libtorrent#2927]
libtorrent version (or branch): `RC_1_1` branch or `libtorrent-1_1_7` tag; `master` is unaffected
platform/architecture: FreeBSD *any* + [Boost 1.67.0](https://reviews.freebsd.org/D15030)
compiler and compiler version: Clang 3.4/4.0/6.0; GCC 6.4.0/7.3.0

```
$ ./bootstrap.sh
$ gmake
[...]
In file included from disk_buffer_holder.cpp:34:
In file included from ../include/libtorrent/aux_/session_impl.hpp:73:
../include/libtorrent/ip_filter.hpp:168:34: error: no member named 'prior' in namespace 'boost'; did you mean
      'perror'?
                        boost::uint32_t last_access = boost::prior(j)->access;
                                                      ^~~~~~~~~~~~
                                                      perror
/usr/include/stdio.h:266:7: note: 'perror' declared here
void     perror(const char *);
         ^
In file included from disk_buffer_holder.cpp:34:
In file included from ../include/libtorrent/aux_/session_impl.hpp:73:
../include/libtorrent/ip_filter.hpp:174:43: error: no member named 'prior' in namespace 'boost'; did you mean
      'perror'?
                        else if (i != m_access_list.begin() && boost::prior(i)->access == flags)
                                                               ^~~~~~~~~~~~
                                                               perror
/usr/include/stdio.h:266:7: note: 'perror' declared here
void     perror(const char *);
         ^
In file included from disk_buffer_holder.cpp:34:
In file included from ../include/libtorrent/aux_/session_impl.hpp:73:
../include/libtorrent/ip_filter.hpp:182:43: error: no member named 'next' in namespace 'boost'
                        if (i != j) m_access_list.erase(boost::next(i), j);
                                                        ~~~~~~~^
3 errors generated.
```

**Comment by arvidn** [comment]
those functions used to be defined in `boost/utility.hpp` but apparently they've moved to `boost/next_prior.hpp`

**Comment by arvidn** [comment]
does this fix it? https://github.com/arvidn/libtorrent/pull/2929

**Comment by jbeich** [comment]
`RC_1_1` branch still fails to build with Boost 1.67.  Applying 64d6b4900448 to `kademlia/routing_table.cpp` appears to help. No more errors after that.
```c++
kademlia/routing_table.cpp:716:33: error: no member named 'next' in namespace 'boost'
        bool const can_split = (boost::next(i) == m_buckets.end()
                                ~~~~~~~^
kademlia/routing_table.cpp:719:40: error: no member named 'prior' in namespace 'boost'
                && (i == m_buckets.begin() || boost::prior(i)->live_nodes.size() > 1);
                                              ~~~~~~~^
2 errors generated.
```

**Comment by arvidn** [comment]
so, like this? https://github.com/arvidn/libtorrent/pull/2937
