### ISSUE TITLE
Current master fails to build with boost-libs-1.70.0

### ISSUE THREAD

**Issue by yurivict** [arvidn/libtorrent#3783]
```
/usr/ports/net-p2p/libtorrent-rasterbar/work/libtorrent-libtorrent_1_2_0-85-g8506f9350/include/libtorrent/udp_socket.hpp:64:50: error: no member named 'get_io_service' in 'boost::asio::basic_datagram_socket<boost::asio::ip::udp, boost::asio::executor>'
                io_service& get_io_service() { return m_socket.get_io_service(); }
                                                      ~~~~~~~~ ^
```

FreeBSD 11.2

**Comment by yurivict** [comment]
Duplicate of https://github.com/arvidn/libtorrent/issues/3683
