### ISSUE TITLE
master branch fails to build with Boost 1.72.0

### ISSUE THREAD

**Issue by jbeich** [arvidn/libtorrent#4083]
Regressed by https://github.com/boostorg/asio/commit/935dad16cb75

```
$ c++ --version
FreeBSD clang version 9.0.0 (tags/RELEASE_900/final 372316) (based on LLVM 9.0.0)
Target: x86_64-unknown-freebsd13.0
Thread model: posix
InstalledDir: /usr/bin
```
```c++
FAILED: CMakeFiles/torrent-rasterbar.dir/src/http_connection.cpp.o
/usr/bin/c++  -DBOOST_ASIO_ENABLE_CANCELIO -DBOOST_ASIO_HAS_STD_CHRONO -DBOOST_ASIO_NO_DEPRECATED -DBOOST_EXCEPTION_DISABLE -DTORRENT_BUILDING_LIBRARY -DTORRENT_BUILDING_SHARED -DTORRENT_USE_ICONV -DTORRENT_USE_LIBCRYPTO -DTORRENT_USE_OPENSSL -D_FILE_OFFSET_BITS=64 -Dtorrent_rasterbar_EXPORTS -I/path/to/libtorrent/include -I/path/to/libtorrent/deps/try_signal -I/path/to/libtorrent/ed25519/src -I/usr/local/include -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -Weverything -Wno-documentation -Wno-c++98-compat-pedantic -Wno-padded -Wno-global-constructors -Wno-exit-time-destructors -Wno-weak-vtables -fexceptions -MD -MT CMakeFiles/torrent-rasterbar.dir/src/http_connection.cpp.o -MF CMakeFiles/torrent-rasterbar.dir/src/http_connection.cpp.o.d -o CMakeFiles/torrent-rasterbar.dir/src/http_connection.cpp.o -c /path/to/libtorrent/src/http_connection.cpp
In file included from /path/to/libtorrent/src/http_connection.cpp:39:
In file included from /path/to/libtorrent/include/libtorrent/http_connection.hpp:54:
In file included from /path/to/libtorrent/include/libtorrent/socket.hpp:58:
In file included from /usr/local/include/boost/asio/write.hpp:1262:
/usr/local/include/boost/asio/impl/write.hpp:425:40: error: no type named 'executor_type' in 'libtorrent::aux::polymorphic_socket<libtorrent::aux::noexcept_move_only<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor> >, libtorrent::socks5_stream, libtorrent::http_stream, libtorrent::aux::utp_stream, libtorrent::i2p_stream, libtorrent::ssl_stream<libtorrent::aux::noexcept_move_only<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor> > >, libtorrent::ssl_stream<libtorrent::socks5_stream>, libtorrent::ssl_stream<libtorrent::http_stream>, libtorrent::ssl_stream<libtorrent::aux::utp_stream> >'
    typedef typename AsyncWriteStream::executor_type executor_type;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
/usr/local/include/boost/asio/impl/write.hpp:534:7: note: in instantiation of template class 'boost::asio::detail::initiate_async_write_buffer_sequence<libtorrent::aux::polymorphic_socket<libtorrent::aux::noexcept_move_only<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor> >, libtorrent::socks5_stream, libtorrent::http_stream, libtorrent::aux::utp_stream, libtorrent::i2p_stream, libtorrent::ssl_stream<libtorrent::aux::noexcept_move_only<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor> > >, libtorrent::ssl_stream<libtorrent::socks5_stream>, libtorrent::ssl_stream<libtorrent::http_stream>, libtorrent::ssl_stream<libtorrent::aux::utp_stream> > >' requested here
      detail::initiate_async_write_buffer_sequence<AsyncWriteStream>(s),
      ^
/path/to/libtorrent/src/http_connection.cpp:269:3: note: in instantiation of function template specialization 'boost::asio::async_write<libtorrent::aux::polymorphic_socket<libtorrent::aux::noexcept_move_only<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor> >, libtorrent::socks5_stream, libtorrent::http_stream, libtorrent::aux::utp_stream, libtorrent::i2p_stream, libtorrent::ssl_stream<libtorrent::aux::noexcept_move_only<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor> > >, libtorrent::ssl_stream<libtorrent::socks5_stream>, libtorrent::ssl_stream<libtorrent::http_stream>, libtorrent::ssl_stream<libtorrent::aux::utp_stream> >, boost::asio::mutable_buffer, std::__1::__bind<void (libtorrent::http_connection::*)(const boost::system::error_code &), std::__1::shared_ptr<libtorrent::http_connection> &, const std::__1::placeholders::__ph<1> &> >' requested here
                async_write(*m_sock, boost::asio::buffer(m_sendbuffer)
                ^
1 error generated.
```

**Comment by arvidn** [comment]
the fix from `RC_1_2` has made it into master now, so this should be resolved
