### ISSUE TITLE
RC_1_1 fail to build with Boost-1.70

### ISSUE THREAD

**Issue by perfect7gentleman** [arvidn/libtorrent#3789]
**Please provide the following information**

libtorrent version (or branch): RC_1_1

platform/architecture: amd64

compiler and compiler version: GCC-8.3

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
```
In file included from ../include/libtorrent/socks5_stream.hpp:44,
                 from ../include/libtorrent/socket_type.hpp:38,
                 from enum_net.cpp:38:
../include/libtorrent/proxy_base.hpp: In member function ‘libtorrent::io_service& libtorrent::proxy_base::get_io_service()’:
../include/libtorrent/proxy_base.hpp:253:17: error: ‘boost::asio::ip::tcp::socket’ {aka ‘class boost::asio::basic_stream_socket<boost::asio::ip::tcp>’} has no member named ‘get_io_service’
   return m_sock.get_io_service();
                 ^~~~~~~~~~~~~~
In file included from ../include/libtorrent/utp_stream.hpp:37,
                 from ../include/libtorrent/socket_type.hpp:41,
                 from enum_net.cpp:38:
../include/libtorrent/udp_socket.hpp: In member function ‘libtorrent::io_service& libtorrent::udp_socket::get_io_service()’:
../include/libtorrent/udp_socket.hpp:83:53: error: ‘boost::asio::ip::udp::socket’ {aka ‘class boost::asio::basic_datagram_socket<boost::asio::ip::udp>’} has no member named ‘get_io_service’
   io_service& get_io_service() { return m_ipv4_sock.get_io_service(); }
                                                     ^~~~~~~~~~~~~~
make[1]: *** [Makefile:1036: enum_net.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from ../include/libtorrent/http_stream.hpp:44,
                 from http_stream.cpp:33:
../include/libtorrent/proxy_base.hpp: In member function ‘libtorrent::io_service& libtorrent::proxy_base::get_io_service()’:
../include/libtorrent/proxy_base.hpp:253:17: error: ‘boost::asio::ip::tcp::socket’ {aka ‘class boost::asio::basic_stream_socket<boost::asio::ip::tcp>’} has no member named ‘get_io_service’
   return m_sock.get_io_service();
                 ^~~~~~~~~~~~~~
make[1]: *** [Makefile:1036: http_stream.lo] Error 1
In file included from ../include/libtorrent/tracker_manager.hpp:74,
                 from ../include/libtorrent/torrent.hpp:59,
                 from choker.cpp:37:
../include/libtorrent/udp_socket.hpp: In member function ‘libtorrent::io_service& libtorrent::udp_socket::get_io_service()’:
../include/libtorrent/udp_socket.hpp:83:53: error: ‘boost::asio::ip::udp::socket’ {aka ‘class boost::asio::basic_datagram_socket<boost::asio::ip::udp>’} has no member named ‘get_io_service’
   io_service& get_io_service() { return m_ipv4_sock.get_io_service(); }
                                                     ^~~~~~~~~~~~~~
In file included from ../include/libtorrent/torrent.hpp:59,
                 from choker.cpp:37:
../include/libtorrent/tracker_manager.hpp: In member function ‘libtorrent::io_service& libtorrent::timeout_handler::get_io_service()’:
../include/libtorrent/tracker_manager.hpp:289:51: error: ‘libtorrent::deadline_timer’ {aka ‘class boost::asio::basic_waitable_timer<std::chrono::_V2::system_clock>’} has no member named ‘get_io_service’
   io_service& get_io_service() { return m_timeout.get_io_service(); }
                                                   ^~~~~~~~~~~~~~
make[1]: *** [Makefile:1036: choker.lo] Error 1
In file included from ../include/libtorrent/tracker_manager.hpp:74,
                 from ../include/libtorrent/torrent.hpp:59,
                 from ../include/libtorrent/web_connection_base.hpp:63,
                 from web_connection_base.cpp:44:
../include/libtorrent/udp_socket.hpp: In member function ‘libtorrent::io_service& libtorrent::udp_socket::get_io_service()’:
../include/libtorrent/udp_socket.hpp:83:53: error: ‘boost::asio::ip::udp::socket’ {aka ‘class boost::asio::basic_datagram_socket<boost::asio::ip::udp>’} has no member named ‘get_io_service’
   io_service& get_io_service() { return m_ipv4_sock.get_io_service(); }
                                                     ^~~~~~~~~~~~~~
In file included from ../include/libtorrent/torrent.hpp:59,
                 from ../include/libtorrent/web_connection_base.hpp:63,
                 from web_connection_base.cpp:44:
../include/libtorrent/tracker_manager.hpp: In member function ‘libtorrent::io_service& libtorrent::timeout_handler::get_io_service()’:
../include/libtorrent/tracker_manager.hpp:289:51: error: ‘libtorrent::deadline_timer’ {aka ‘class boost::asio::basic_waitable_timer<std::chrono::_V2::system_clock>’} has no member named ‘get_io_service’
   io_service& get_io_service() { return m_timeout.get_io_service(); }
                                                   ^~~~~~~~~~~~~~
make[1]: *** [Makefile:1036: web_connection_base.lo] Error 1
In file included from ../include/libtorrent/tracker_manager.hpp:74,
                 from ../include/libtorrent/torrent.hpp:59,
                 from alert.cpp:43:
../include/libtorrent/udp_socket.hpp: In member function ‘libtorrent::io_service& libtorrent::udp_socket::get_io_service()’:
../include/libtorrent/udp_socket.hpp:83:53: error: ‘boost::asio::ip::udp::socket’ {aka ‘class boost::asio::basic_datagram_socket<boost::asio::ip::udp>’} has no member named ‘get_io_service’
   io_service& get_io_service() { return m_ipv4_sock.get_io_service(); }
                                                     ^~~~~~~~~~~~~~
In file included from ../include/libtorrent/torrent.hpp:59,
                 from alert.cpp:43:
../include/libtorrent/tracker_manager.hpp: In member function ‘libtorrent::io_service& libtorrent::timeout_handler::get_io_service()’:
../include/libtorrent/tracker_manager.hpp:289:51: error: ‘libtorrent::deadline_timer’ {aka ‘class boost::asio::basic_waitable_timer<std::chrono::_V2::system_clock>’} has no member named ‘get_io_service’
   io_service& get_io_service() { return m_timeout.get_io_service(); }
                                                   ^~~~~~~~~~~~~~
make[1]: *** [Makefile:1036: alert.lo] Error 1
In file included from ../include/libtorrent/tracker_manager.hpp:74,
                 from ../include/libtorrent/torrent.hpp:59,
                 from ../include/libtorrent/bt_peer_connection.hpp:60,
                 from bt_peer_connection.cpp:48:
../include/libtorrent/udp_socket.hpp: In member function ‘libtorrent::io_service& libtorrent::udp_socket::get_io_service()’:
../include/libtorrent/udp_socket.hpp:83:53: error: ‘boost::asio::ip::udp::socket’ {aka ‘class boost::asio::basic_datagram_socket<boost::asio::ip::udp>’} has no member named ‘get_io_service’
   io_service& get_io_service() { return m_ipv4_sock.get_io_service(); }
                                                     ^~~~~~~~~~~~~~
In file included from ../include/libtorrent/torrent.hpp:59,
                 from ../include/libtorrent/bt_peer_connection.hpp:60,
                 from bt_peer_connection.cpp:48:
../include/libtorrent/tracker_manager.hpp: In member function ‘libtorrent::io_service& libtorrent::timeout_handler::get_io_service()’:
../include/libtorrent/tracker_manager.hpp:289:51: error: ‘libtorrent::deadline_timer’ {aka ‘class boost::asio::basic_waitable_timer<std::chrono::_V2::system_clock>’} has no member named ‘get_io_service’
   io_service& get_io_service() { return m_timeout.get_io_service(); }
                                                   ^~~~~~~~~~~~~~
In file included from ../include/libtorrent/socks5_stream.hpp:44,
                 from ../include/libtorrent/socket_type.hpp:38,
                 from bt_peer_connection.cpp:65:
../include/libtorrent/proxy_base.hpp: In member function ‘libtorrent::io_service& libtorrent::proxy_base::get_io_service()’:
../include/libtorrent/proxy_base.hpp:253:17: error: ‘boost::asio::ip::tcp::socket’ {aka ‘class boost::asio::basic_stream_socket<boost::asio::ip::tcp>’} has no member named ‘get_io_service’
   return m_sock.get_io_service();
                 ^~~~~~~~~~~~~~
make[1]: *** [Makefile:1036: bt_peer_connection.lo] Error 1
In file included from ../include/libtorrent/tracker_manager.hpp:74,
                 from ../include/libtorrent/aux_/session_impl.hpp:70,
                 from disk_buffer_holder.cpp:34:
../include/libtorrent/udp_socket.hpp: In member function ‘libtorrent::io_service& libtorrent::udp_socket::get_io_service()’:
../include/libtorrent/udp_socket.hpp:83:53: error: ‘boost::asio::ip::udp::socket’ {aka ‘class boost::asio::basic_datagram_socket<boost::asio::ip::udp>’} has no member named ‘get_io_service’
   io_service& get_io_service() { return m_ipv4_sock.get_io_service(); }
                                                     ^~~~~~~~~~~~~~
In file included from ../include/libtorrent/aux_/session_impl.hpp:70,
                 from disk_buffer_holder.cpp:34:
../include/libtorrent/tracker_manager.hpp: In member function ‘libtorrent::io_service& libtorrent::timeout_handler::get_io_service()’:
../include/libtorrent/tracker_manager.hpp:289:51: error: ‘libtorrent::deadline_timer’ {aka ‘class boost::asio::basic_waitable_timer<std::chrono::_V2::system_clock>’} has no member named ‘get_io_service’
   io_service& get_io_service() { return m_timeout.get_io_service(); }
                                                   ^~~~~~~~~~~~~~
In file included from ../include/libtorrent/socks5_stream.hpp:44,
                 from ../include/libtorrent/socket_type.hpp:38,
                 from ../include/libtorrent/aux_/session_impl.hpp:80,
                 from disk_buffer_holder.cpp:34:
../include/libtorrent/proxy_base.hpp: In member function ‘libtorrent::io_service& libtorrent::proxy_base::get_io_service()’:
../include/libtorrent/proxy_base.hpp:253:17: error: ‘boost::asio::ip::tcp::socket’ {aka ‘class boost::asio::basic_stream_socket<boost::asio::ip::tcp>’} has no member named ‘get_io_service’
   return m_sock.get_io_service();
                 ^~~~~~~~~~~~~~
make[1]: *** [Makefile:1036: disk_buffer_holder.lo] Error 1
In file included from ../include/libtorrent/socks5_stream.hpp:44,
                 from ../include/libtorrent/socket_type.hpp:38,
                 from ../include/libtorrent/http_connection.hpp:67,
                 from http_connection.cpp:33:
../include/libtorrent/proxy_base.hpp: In member function ‘libtorrent::io_service& libtorrent::proxy_base::get_io_service()’:
../include/libtorrent/proxy_base.hpp:253:17: error: ‘boost::asio::ip::tcp::socket’ {aka ‘class boost::asio::basic_stream_socket<boost::asio::ip::tcp>’} has no member named ‘get_io_service’
   return m_sock.get_io_service();
                 ^~~~~~~~~~~~~~
In file included from ../include/libtorrent/utp_stream.hpp:37,
                 from ../include/libtorrent/socket_type.hpp:41,
                 from ../include/libtorrent/http_connection.hpp:67,
                 from http_connection.cpp:33:
../include/libtorrent/udp_socket.hpp: In member function ‘libtorrent::io_service& libtorrent::udp_socket::get_io_service()’:
../include/libtorrent/udp_socket.hpp:83:53: error: ‘boost::asio::ip::udp::socket’ {aka ‘class boost::asio::basic_datagram_socket<boost::asio::ip::udp>’} has no member named ‘get_io_service’
   io_service& get_io_service() { return m_ipv4_sock.get_io_service(); }
                                                     ^~~~~~~~~~~~~~
http_connection.cpp: In member function ‘void libtorrent::http_connection::get(const string&, libtorrent::time_duration, int, const libtorrent::aux::proxy_settings*, int, const string&, boost::optional<boost::asio::ip::address>, int, const string&, libtorrent::i2p_connection*)’:
http_connection.cpp:153:11: error: ‘libtorrent::deadline_timer’ {aka ‘class boost::asio::basic_waitable_timer<std::chrono::_V2::system_clock>’} has no member named ‘get_io_service’
   m_timer.get_io_service().post(boost::bind(&http_connection::callback
           ^~~~~~~~~~~~~~
http_connection.cpp:165:11: error: ‘libtorrent::deadline_timer’ {aka ‘class boost::asio::basic_waitable_timer<std::chrono::_V2::system_clock>’} has no member named ‘get_io_service’
   m_timer.get_io_service().post(boost::bind(&http_connection::callback
           ^~~~~~~~~~~~~~
http_connection.cpp: In member function ‘void libtorrent::http_connection::start(const string&, int, libtorrent::time_duration, int, const libtorrent::aux::proxy_settings*, bool, int, boost::optional<boost::asio::ip::address>, int, libtorrent::i2p_connection*)’:
http_connection.cpp:266:11: error: ‘libtorrent::deadline_timer’ {aka ‘class boost::asio::basic_waitable_timer<std::chrono::_V2::system_clock>’} has no member named ‘get_io_service’
   m_timer.get_io_service().post(boost::bind(&http_connection::callback
           ^~~~~~~~~~~~~~
http_connection.cpp:306:13: error: ‘libtorrent::deadline_timer’ {aka ‘class boost::asio::basic_waitable_timer<std::chrono::_V2::system_clock>’} has no member named ‘get_io_service’
     m_timer.get_io_service().post(boost::bind(&http_connection::callback
             ^~~~~~~~~~~~~~
http_connection.cpp:340:15: error: ‘libtorrent::deadline_timer’ {aka ‘class boost::asio::basic_waitable_timer<std::chrono::_V2::system_clock>’} has no member named ‘get_io_service’
       m_timer.get_io_service().post(boost::bind(&http_connection::callback
               ^~~~~~~~~~~~~~
http_connection.cpp:352:34: error: ‘libtorrent::deadline_timer’ {aka ‘class boost::asio::basic_waitable_timer<std::chrono::_V2::system_clock>’} has no member named ‘get_io_service’
   instantiate_connection(m_timer.get_io_service()
                                  ^~~~~~~~~~~~~~
http_connection.cpp:361:13: error: ‘libtorrent::deadline_timer’ {aka ‘class boost::asio::basic_waitable_timer<std::chrono::_V2::system_clock>’} has no member named ‘get_io_service’
     m_timer.get_io_service().post(boost::bind(&http_connection::callback
             ^~~~~~~~~~~~~~
http_connection.cpp:370:12: error: ‘libtorrent::deadline_timer’ {aka ‘class boost::asio::basic_waitable_timer<std::chrono::_V2::system_clock>’} has no member named ‘get_io_service’
    m_timer.get_io_service().post(boost::bind(&http_connection::callback
            ^~~~~~~~~~~~~~
make[1]: *** [Makefile:1036: http_connection.lo] Error 1
In file included from ../include/libtorrent/tracker_manager.hpp:74,
                 from ../include/libtorrent/torrent.hpp:59,
                 from ../include/libtorrent/web_connection_base.hpp:63,
                 from ../include/libtorrent/http_seed_connection.hpp:55,
                 from http_seed_connection.cpp:43:
../include/libtorrent/udp_socket.hpp: In member function ‘libtorrent::io_service& libtorrent::udp_socket::get_io_service()’:
../include/libtorrent/udp_socket.hpp:83:53: error: ‘boost::asio::ip::udp::socket’ {aka ‘class boost::asio::basic_datagram_socket<boost::asio::ip::udp>’} has no member named ‘get_io_service’
   io_service& get_io_service() { return m_ipv4_sock.get_io_service(); }
                                                     ^~~~~~~~~~~~~~
In file included from ../include/libtorrent/torrent.hpp:59,
                 from ../include/libtorrent/web_connection_base.hpp:63,
                 from ../include/libtorrent/http_seed_connection.hpp:55,
                 from http_seed_connection.cpp:43:
../include/libtorrent/tracker_manager.hpp: In member function ‘libtorrent::io_service& libtorrent::timeout_handler::get_io_service()’:
../include/libtorrent/tracker_manager.hpp:289:51: error: ‘libtorrent::deadline_timer’ {aka ‘class boost::asio::basic_waitable_timer<std::chrono::_V2::system_clock>’} has no member named ‘get_io_service’
   io_service& get_io_service() { return m_timeout.get_io_service(); }
                                                   ^~~~~~~~~~~~~~
In file included from ../include/libtorrent/socks5_stream.hpp:44,
                 from ../include/libtorrent/socket_type.hpp:38,
                 from ../include/libtorrent/aux_/session_impl.hpp:80,
                 from http_seed_connection.cpp:52:
../include/libtorrent/proxy_base.hpp: In member function ‘libtorrent::io_service& libtorrent::proxy_base::get_io_service()’:
../include/libtorrent/proxy_base.hpp:253:17: error: ‘boost::asio::ip::tcp::socket’ {aka ‘class boost::asio::basic_stream_socket<boost::asio::ip::tcp>’} has no member named ‘get_io_service’
   return m_sock.get_io_service();
                 ^~~~~~~~~~~~~~
make[1]: *** [Makefile:1036: http_seed_connection.lo] Error 1
make[1]: Leaving directory '/tmp/portage/net-libs/libtorrent-rasterbar-1.1.9999/work/libtorrent-rasterbar-1.1.9999/src'
make: *** [Makefile:625: all-recursive] Error 1
```

**Comment by arvidn** [comment]
you could try apply a patch similar to this: https://github.com/arvidn/libtorrent/pull/3788

**Comment by perfect7gentleman** [comment]
```
/tmp/portage/net-libs/libtorrent-rasterbar-1.1.9999/work/libtorrent-rasterbar-1.1.9999 # patch -p1 -i  3788.patch 
patching file include/libtorrent/config.hpp
Hunk #1 FAILED at 38.
Hunk #2 succeeded at 91 with fuzz 2 (offset 35 lines).
1 out of 2 hunks FAILED -- saving rejects to file include/libtorrent/config.hpp.rej
patching file include/libtorrent/proxy_base.hpp
Hunk #1 succeeded at 250 (offset 4 lines).
patching file include/libtorrent/tracker_manager.hpp
Hunk #1 succeeded at 286 with fuzz 2 (offset 27 lines).
patching file include/libtorrent/udp_socket.hpp
Hunk #1 FAILED at 61.
1 out of 1 hunk FAILED -- saving rejects to file include/libtorrent/udp_socket.hpp.rej
can't find file to patch at input line 93
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/disk_io_thread_pool.cpp b/src/disk_io_thread_pool.cpp
|index 4d4b5ee678..72a3523f5e 100644
|--- a/src/disk_io_thread_pool.cpp
|+++ b/src/disk_io_thread_pool.cpp
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
1 out of 1 hunk ignored
patching file src/http_connection.cpp
Hunk #1 FAILED at 148.
Hunk #2 FAILED at 160.
Hunk #3 FAILED at 258.
Hunk #4 FAILED at 297.
Hunk #5 FAILED at 332.
Hunk #6 FAILED at 344.
Hunk #7 FAILED at 353.
Hunk #8 FAILED at 362.
8 out of 8 hunks FAILED -- saving rejects to file src/http_connection.cpp.rej
patching file src/kademlia/dht_tracker.cpp
Hunk #1 FAILED at 130.
1 out of 1 hunk FAILED -- saving rejects to file src/kademlia/dht_tracker.cpp.rej
patching file src/lsd.cpp
Hunk #1 FAILED at 100.
1 out of 1 hunk FAILED -- saving rejects to file src/lsd.cpp.rej
patching file src/natpmp.cpp
Hunk #1 FAILED at 160.
Hunk #2 FAILED at 194.
2 out of 2 hunks FAILED -- saving rejects to file src/natpmp.cpp.rej
patching file src/udp_socket.cpp
Hunk #1 FAILED at 492.
1 out of 1 hunk FAILED -- saving rejects to file src/udp_socket.cpp.rej
patching file src/upnp.cpp
Hunk #1 FAILED at 121.
1 out of 1 hunk FAILED -- saving rejects to file src/upnp.cpp.rej
patching file include/libtorrent/config.hpp
Hunk #1 FAILED at 38.
Hunk #2 succeeded at 91 with fuzz 2 (offset 34 lines).
1 out of 2 hunks FAILED -- saving rejects to file include/libtorrent/config.hpp.rej
patching file include/libtorrent/io_service.hpp
Hunk #1 FAILED at 38.
1 out of 1 hunk FAILED -- saving rejects to file include/libtorrent/io_service.hpp.rej
patching file include/libtorrent/io_service_fwd.hpp
Hunk #1 succeeded at 65 with fuzz 2 (offset 10 lines).
patching file include/libtorrent/proxy_base.hpp
Hunk #1 succeeded at 250 (offset 4 lines).
patching file include/libtorrent/tracker_manager.hpp
Hunk #1 succeeded at 286 with fuzz 2 (offset 27 lines).
patching file include/libtorrent/udp_socket.hpp
Hunk #1 FAILED at 61.
1 out of 1 hunk FAILED -- saving rejects to file include/libtorrent/udp_socket.hpp.rej
can't find file to patch at input line 400
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/disk_io_thread_pool.cpp b/src/disk_io_thread_pool.cpp
|index 72a3523f5e..123159a45d 100644
|--- a/src/disk_io_thread_pool.cpp
|+++ b/src/disk_io_thread_pool.cpp
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
1 out of 1 hunk ignored
patching file src/http_connection.cpp
Hunk #1 FAILED at 148.
Hunk #2 FAILED at 160.
Hunk #3 FAILED at 258.
Hunk #4 FAILED at 297.
Hunk #5 FAILED at 332.
Hunk #6 FAILED at 344.
Hunk #7 FAILED at 353.
Hunk #8 FAILED at 362.
8 out of 8 hunks FAILED -- saving rejects to file src/http_connection.cpp.rej
patching file src/kademlia/dht_tracker.cpp
Hunk #1 FAILED at 130.
1 out of 1 hunk FAILED -- saving rejects to file src/kademlia/dht_tracker.cpp.rej
patching file src/lsd.cpp
Hunk #1 FAILED at 100.
1 out of 1 hunk FAILED -- saving rejects to file src/lsd.cpp.rej
patching file src/natpmp.cpp
Hunk #1 FAILED at 160.
Hunk #2 FAILED at 194.
2 out of 2 hunks FAILED -- saving rejects to file src/natpmp.cpp.rej
patching file src/udp_socket.cpp
Hunk #1 FAILED at 492.
1 out of 1 hunk FAILED -- saving rejects to file src/udp_socket.cpp.rej
patching file src/upnp.cpp
Hunk #1 FAILED at 121.
1 out of 1 hunk FAILED -- saving rejects to file src/upnp.cpp.rej
patching file test/test_fast_extension.cpp
Hunk #1 succeeded at 453 with fuzz 2 (offset -9 lines).
```

**Comment by arvidn** [comment]
I said "similar", not the same patch. i.e. make the same kinds of changes as that patch did to `RC_1_2`
