### ISSUE TITLE
libtorrent 1.1.1 causes "missing files" with qBittorrent after launching the following time

### ISSUE THREAD

**Issue by najjara** [arvidn/libtorrent#1177]
libtorrent version (or branch): 1.1.1

platform/architecture: Linux 4.7.5 amd64 (Arch Linux)

compiler and compiler version: gcc 6.2.1, boost 1.61.0

I've opened an issue with the qBT project (qbittorrent/qBittorrent/issues/5781) during which I compiled qBT 3.3.7 against libtorrent 1.0.10, instead of 1.1.1 as in the package provided in the Arch repo. The problem stopped.

The .fastresume created doesn't hold file progress. So after each quit, seeding or leeching torrents will show a small progress (e.g. 1.2%) and "Missing files". I need to force a recheck to account for the data again.

(I tried compiling the latest master branch, but it gives this error on `make`:)

```
peer_connection.cpp:505:52: error: no matching function for call to ‘libtorrent::alert_manager::emplace_alert(libtorrent::torrent_handle&, const endpoint&, const peer_id&, libtorrent::peer_log_alert::direction_t&, const char*&, const char*&, va_list)’
    h, m_remote, m_peer_id, direction, event, fmt, v);
                                                    ^
In file included from peer_connection.cpp:60:0:
../include/libtorrent/alert_manager.hpp:62:8: note: candidate: void libtorrent::alert_manager::emplace_alert(Args&& ...) [with T = libtorrent::peer_log_alert; Args = {libtorrent::torrent_handle&, const boost::asio::ip::basic_endpoint<boost::asio::ip::tcp>&, const libtorrent::digest32<160>&, libtorrent::peer_log_alert::direction_t&, const char*&, const char*&, __va_list_tag (&)[1]}]
   void emplace_alert(Args&&... args)
        ^~~~~~~~~~~~~
../include/libtorrent/alert_manager.hpp:62:8: note:   no known conversion for argument 7 from ‘va_list {aka __va_list_tag [1]}’ to ‘__va_list_tag (&)[1]’
make[1]: *** [Makefile:937: peer_connection.lo] Error 1
make[1]: Leaving directory '/home/user/git/libtorrent/src'
make: *** [Makefile:618: all-recursive] Error 1
```

**Comment by arvidn** [comment]
the error is probably because your compiler doesn't fully support c++11, but I would kind of expect some other error to be the first. Do you have an example fastresume file that works in 1.0.10 but fails in 1.1.1?

I imagine that the problem is mainly a resume file saved by 1.0.10 isn't loaded properly in 1.1.1, but a file saved with 1.1.1 works with itself. Is that the case? or are you experiencing that resume files saved with 1.1.1 fail to load correctly with 1.1.1 itself?

**Comment by najjara** [comment]
> I imagine that the problem is mainly a resume file saved by 1.0.10 isn't loaded properly in 1.1.1, but a file saved with 1.1.1 works with itself. Is that the case? or are you experiencing that resume files saved with 1.1.1 fail to load correctly with 1.1.1 itself?

The issue was with libtorrent 1.1.1 wholly. I didn't mix torrents, and I made sure to delete everything. The idea to compile against 1.0.10 came from sledgehammer999 to see if it's a libtorrent issue, or qBT one. A file saved with 1.1.1 fails to load correctly with itself.

Here's a fastresume file created by 1.1.1 and fails to be loaded with 1.1.1: [fe732fd8fb37915775726ef7eb0643f13ced8789.fastresume.zip](https://github.com/qbittorrent/qBittorrent/files/504201/fe732fd8fb37915775726ef7eb0643f13ced8789.fastresume.zip)

Here's a fastresume by 1.0.10 (no problems): 
[fe732fd8fb37915775726ef7eb0643f13ced8789.fastresume.zip](https://github.com/arvidn/libtorrent/files/506685/fe732fd8fb37915775726ef7eb0643f13ced8789.fastresume.zip)

**Comment by arvidn** [comment]
That resume file has the file size of the first file as 0 bytes, which is incorrect. I'll try to figure out how it can end up with that impression

**Comment by arvidn** [comment]
hm, when I make it generate resume data for this torrent it does get the file size for the files right. My suspicion is that it's related to the stat_cache, somehow getting a stale state

**Comment by arvidn** [comment]
I've started looking at this. I haven't found anything wrong yet, just added some unit test coverage. Are there any distinguishing properties of the torrents this happens to? the first time the file is created perhaps? are you using partfiles? do the torrents have padfiles?

I'm doing this in a branch off of 1.1. https://github.com/arvidn/libtorrent/pull/1248

**Comment by najjara** [comment]
I can't say for sure, but I guess they're Magnet URIs.
No padfiles, and no partfiles

**Comment by arvidn** [comment]
I'm onto something with this test failure. https://github.com/arvidn/libtorrent/pull/1248

**Comment by arvidn** [comment]
I founds some minor issues, potentially causing the stat-cache to be stale, but I don't have very high hopes that these were the underlying causes for the missing file sizes in the resume data.

I have experienced similar issues in ``client_test``, but I'm convinced this was caused by a bug in client_test.cpp, where failed to update an info-hash -> filename map entry once the metadata was downloaded and the .torrent file was saved. This caused the resume data for the session where the magnet link was added to be saved under an incorrect filename. The next startup always had to check the files. I fixed this in the same PR. @najjara the resume files you provided though, I take it they were both saved in the same (correct) location and does get picked up on restart (I just wonder if there's a risk qBT has a similar issue where the magnet-link case fails in some regard).

Perhaps the most important thing I added though was an invariant checker that, whenever saving resume data, double-checks the data pulled out from the stat cache with the files on the filesystem (by issuing additional ``stat()`` calls). This is only enabled when invariants are enabled. @sledgehammer999 would it make sense to make a test build with libtorrent invariant checks enabled? based on RC_1_1 (as soon as I've landed this PR)

**Comment by arvidn** [comment]
(patch is in RC_1_1 now)

**Comment by sledgehammer999** [comment]
IIRC @najjara has Arch linux and I can't provide builds for that. But I think he is able to compile and test the RC_1_1 branch.

**Comment by najjara** [comment]
I'm willing to compile and test.
Do the invariant checks require anything on qBT's part, or do I just compile against RC_1_1?

**Comment by arvidn** [comment]
Just make sure to build libtorrent with invariant checks enabled. you shouldn't need any qBT changes

**Comment by najjara** [comment]
Where do I pass the flag?
I can't find that info in `./configure --help`

**Comment by najjara** [comment]
I did `./configure --enable-debug --enable-invariant-checks`, then `make && make install`. However, I don't have a lib for libtorrent (`ldconfig -p |grep libtorrent` is blank). qBT keeps failing because it can't see that I have libtorrent (`pkg-config --list-all` doesn't output libtorrent either).

**Comment by najjara** [comment]
assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
    Please include the following information:

    version: 1.1.1.0-1229491

    file: 'block_cache.cpp'
    line: 761
    function: libtorrent::cached_piece_entry* libtorrent::block_cache::add_dirty_block(libtorrent::disk_io_job*)
    expression: std::find(m_deleted_storages.begin(), m_deleted_storages.end() , std::make_pair(j->storage->files()->name() , static_cast<void const*>(j->storage->files()))) == m_deleted_storages.end()

    stack:
    1: assert_fail(char const*, int, char const*, char const*, char const*, int)
    2: 
    3: 
    4: 
    5: 
    6: 
    7: 
    8: 
    9: 
    10: 
    11: 
    12: 
    13: 
    14: 
    15: clone

    Catching signal: SIGINT
    Exiting cleanly


    *************************************************************
    Catching signal: SIGABRT
    Please file a bug report at http://bug.qbittorrent.org and provide the following information:

    qBittorrent version: v3.3.7
    stack trace:
      /usr/lib/libc.so.6 : gsignal()+0xcf  [0x7f9f129e004f]
      /usr/lib/libc.so.6 : abort()+0x16a  [0x7f9f129e147a]
      /usr/lib/libtorrent-rasterbar.so.9 : assert_fail(char const*, int, char const*, char const*, char const*, int)+0x9b  [0x7f9f15939c6b]
      /usr/lib/libtorrent-rasterbar.so.9 : ()+0xaa7b5  [0x7f9f159547b5]
      /usr/lib/libtorrent-rasterbar.so.9 : ()+0xd88b5  [0x7f9f159828b5]
      /usr/lib/libtorrent-rasterbar.so.9 : ()+0x1837c2  [0x7f9f15a2d7c2]
      /usr/lib/libtorrent-rasterbar.so.9 : ()+0x1843d5  [0x7f9f15a2e3d5]
      /usr/lib/libtorrent-rasterbar.so.9 : ()+0xb4489  [0x7f9f1595e489]
      /usr/lib/libtorrent-rasterbar.so.9 : ()+0xb24f1  [0x7f9f1595c4f1]
      /usr/lib/libtorrent-rasterbar.so.9 : ()+0xb8472  [0x7f9f15962472]
      /usr/lib/libtorrent-rasterbar.so.9 : ()+0xba20a  [0x7f9f1596420a]
      /usr/lib/libtorrent-rasterbar.so.9 : ()+0x1883fb  [0x7f9f15a323fb]
      /usr/lib/libtorrent-rasterbar.so.9 : ()+0x194c6d  [0x7f9f15a3ec6d]
      /usr/lib/libtorrent-rasterbar.so.9 : ()+0x1f6575  [0x7f9f15aa0575]
      /usr/lib/libtorrent-rasterbar.so.9 : ()+0xda02f  [0x7f9f1598402f]
      /usr/lib/libpthread.so.0 : ()+0x7454  [0x7f9f135f5454]
      /usr/lib/libc.so.6 : clone()+0x5f  [0x7f9f12a957df]
    Aborted (core dumped)

This is what I got when I very first added the URI. But then I started it again, and it begun downloading. I tried it twice (delete torrent, then add again). When I first add a magnet, just as the torrent starts qBT crashes. Then I start it the second time and it runs without a problem

---------------
On the other hand, the original problem isn't gone. It's still there. (same torrent, to keep a constant reference)
The fastresume: [fe732fd8fb37915775726ef7eb0643f13ced8789.fastresume.zip](https://github.com/arvidn/libtorrent/files/550885/fe732fd8fb37915775726ef7eb0643f13ced8789.fastresume.zip)

**Comment by arvidn** [comment]
interesting. that assert fires when blocks are being written to the storage for a torrent that has been deleted. I have no idea why the torrent would get removed. Specifically when the files for that torrent were deleted.

@sledgehammer999 does qBT remove and re-add torrents when they receive metadata?

**Comment by sledgehammer999** [comment]
>@sledgehammer999 does qBT remove and re-add torrents when they receive metadata?

We do that in a very specific case. When a user adds a torrent/magnet a dialog is presented to him for save path/labels/option/info. In the case of a magnet the magnet is added silently in the background to the session in order to preload the metadata, so we can show the file structure to the user if he wants to wait with the dialog open. So when the metadata are received while the dialog is still open we hold the torrent_info data and remove the torrent from the session. If the user accepts the dialog we re-add the torrent using the new settings the user chose. Otherwise, we discard the saved torrent_info.

@najjara for the purposes of testing you can bypass the above described handling. Just go to the Options and disable `Display torrent content and some options` under the `Downloads` category/tab.

**Comment by najjara** [comment]
It doesn't crash after the bypass

**Comment by sledgehammer999** [comment]
>It doesn't crash after the bypass

Does it save the fastresume correctly?

**Comment by najjara** [comment]
@sledgehammer999 Unless the bypass changes how the fastresume I don't think it does. The crash is just a side effect

> On the other hand, the original problem isn't gone. It's still there. (same torrent, to keep a constant reference)
The fastresume: fe732fd8fb37915775726ef7eb0643f13ced8789.fastresume.zip

However, I'm testing

**Comment by najjara** [comment]
@sledgehammer999 @arvidn Here's something that I've noticed, dialog or not, is when the torrent is partially selected the fastresume problem happens (if it has 3 files for example, and I select just one)

**Comment by arvidn** [comment]
I think I know what's going on. The file size recorded in the resume data for the first file is 0, because it doesn't exist. It has priority 0 and is therefore backed by the partfile. However, when the torrent is loaded, the file priorities are not taken into account, and since we see a partial piece that should have been written to the first file, we expect it to exist on disk. This is what's causing the resume data to fail. I will fix RC_1_1 to not have any expectation of files with priority 0 to exist on disk.

**Comment by arvidn** [comment]
@najjara would you mind giving this patch a try? https://github.com/arvidn/libtorrent/pull/1268

**Comment by najjara** [comment]
@arvidn I think that solves it

@sledgehammer999 The problem of crashing after adding a torrent is still present, however

**Comment by sledgehammer999** [comment]
@arvidn forgive me if I am wrong but isn't this also a bug in libtorrent?
Also in the use case I described [here ](https://github.com/arvidn/libtorrent/issues/1177#issuecomment-256456534) we specifically set the `flag_upload_mode` flag. We want to prevent a race condition here. After we download the metadata in the background we remove it from session until user decides what to do with it. But in the meantime, until the alert is handled and remove() is called, we don't want it to start downloading data to the tmp path.

**Comment by arvidn** [comment]
@sledgehammer999 yes, absolutely. libtorrent is never supposed to assert (with the exception of precondition checks, but those are clearly labeled as such). I assume you're referring to the assert from deleting the torrent immediately after receiving metadata.

**Comment by arvidn** [comment]
@najjara 
> But why such a low completion percentage? Why not just the % that is the missing files' sizes?

What do you mean? The problem was that libtorrent would force a full recheck of the files, right? not that it would fail to recognize previously downloaded data.

**Comment by najjara** [comment]
@arvidn That's partially true. The problem was that libtorrent would only recognize a small percentage of the completed torrent, and report missing data, which would *force me* to do a recheck:

>The .fastresume created doesn't hold file progress. So after each quit, seeding or leeching torrents will show a small progress (e.g. 1.2%) and "Missing files". I need to force a recheck to account for the data again.

I'm just curious as to why it only recognized that small percentage. Why 1.2% or 2.3% for example?
Just curiosity.

**Comment by arvidn** [comment]
Is this still the case? with that patch? if

**Comment by arvidn** [comment]
I would have expected the behavior before my patch to cause the resume data verification to fail and automatically trigger a recheck of the files. you're saying that wasn't the case?

and I would expect the behavior with the patch (which I've merged into the 1.1 branch now) to correctly verify the resume data and also correctly fully restore the download progress from the previous session.

@sledgehammer999 would you mind filing a new issue for the assert when removing the torrent immediately after the metadata is received. please provide details on which settings you use and which alert you trigger the removal on.

**Comment by najjara** [comment]
@arvidn the problem of "missing data" is gone with the patch, as far as my testing shows. Before the patch no there was no forced recheck after failing. I had to right click > force recheck, otherwise the torrent would just sit there showing "error: missing data" not doing anything

**Comment by arvidn** [comment]
ok, I'll consider this closed then. If an issue like this pops up after next release, of 1.1.2, please open a new issue
